services:
  db_mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

#  java_app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db_mysql